### PR TITLE
Major refactoring & upgrade to version 2.9.0

### LINKED ISSUE #1: Upgrade from previous version
Hi !

I'm using a previous version of Piwigo YNH package, and the upgrade script is not yet available.
Have you planned to provide an upgrade script or I'll have to do the update by hand ?

Thanks,

Léo :fr:

### LINKED ISSUE #6: Version 2.9.0
Hi all, salut à tous,

2.9.0 version of Piwigo is out !

Léo

### PR DESCRIPTION
**Pull request by JimboJoe**
1. Major refactoring & complete Piwigo upgrade process:
- refactoring to comply with packaging latest standards/helpers
- use Piwigo internal upgrade process via a curl command (closes #1)

2. Upgrade Piwigo version to 2.9.0 (closes #6)

### CODE REVIEW

**Comment by JimboJoe** [comment]
@LeOSW42 Can  you please possibly test/review that upgrade before I merge it?

**Comment by LeOSW42** [comment]
I'll test that this week-end.

**Comment by LeOSW42** [comment]
I had no problem with the update in my production server with many plugins installed:
 * OpenStreetMap
 * Batch Downloader
 * Community
 * Fotorama
 * Ldap Login
 * Localfiles Editor
 * Take a Tour
 * VideoJS

I had three warnings during install:
````
Attention : The helper ynh_mkdir_tmp is deprecated.
Attention : You should use 'mktemp -d' instead and manage permissions properly with chmod/chown.
Attention : 2017-06-04 15:59:57 URL:http://piwigo.org/download/dlcounter.php?code=2.9.0 [7763733/7763733] -> "app.zip" [1]
````

I also tried to do a backup with that new package version (didn't used the restore from backup function), no warning outputed.

Léo

**Comment by JimboJoe** [comment]
Thanks a lot for your test!
I did try to restore a backed up instance with success so I guess we can release this 👍

**Pull request merged**
