### PR TITLE
Protect with fail2ban (closes #8)

### LINKED ISSUE #8: Set-up fail2ban rules
Thanks to [this plugin](http://piwigo.org/ext/extension_view.php?eid=801), it seems possible to log failed logins and apply a fail2ban rule to protect against brute-force attack.
It would be useful to get this plugin automatically installed and activated at installation and upgrade.

### PR DESCRIPTION
**Pull request by JimboJoe**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Seems good to me, but on which part of this PR would you like my review ? Fail2ban ?

**Comment by JimboJoe** [comment]
Yes, fail2ban and naming, directory setting conventions... to be compared to [this](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/40), for example.

**Comment by maniackcrudelis** [comment]
All seems good.
But, we need to test if that works well.

And, I'll glad to see this as an helper instead.
But, first, we should try it.

**Comment by JimboJoe** [comment]
I've tested this, and it indeed works! ;-)
As for the helper, I don't see it as a very "smart" one because, besides copying the 2 right files (replacing the app name) and restarting the fail2ban service, I think the configuration can be very different from one app to another one...

**Comment by maniackcrudelis** [comment]
I think really we can make a simple helper, because we have only to change the failregex and the log. That's all.
In the most case, that should works.

And, it can be a good thing if we can expand this to all our apps.

**Comment by JimboJoe** [comment]
Yep, I see what you mean: in most cases for HTTP(S) ports, configuration files will look alike.
I'll try to come up with something!

**Pull request merged**
