### PR TITLE
Force https

### PR DESCRIPTION
**Pull request by anmol26s**
## Problem

The app is not forcing https, due to which app needs to be manually opened in https to make the communication secure
## Solution

Add these line to nginx.conf
```
if ($scheme = http) {
        rewrite ^ https://$server_name$request_uri? permanent;
}
```
## PR Status

- [x] Code finished.
- [ ]     Tested with Package_check.
- [ ]     Upgrade from last version tested.
- [X]     Can be reviewed and tested.

## Validation
Micro decision. 

- [x]  Code review : JimboJoe
- [x]  Approval (LGTM) : JimboJoe
- [x]  Approval (LGTM) : Josué

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/piwigo_ynh%20PR29%20(Official_fork)/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by anmol26s** [comment]
@YunoHost-Apps/apps-group 
Can you review?

**Comment by Josue-T** [comment]
Will be merged in 3 days

**Comment by anmol26s** [comment]
3 days ... :stuck_out_tongue_winking_eye:

**Comment by anmol26s** [comment]
Can we merge it?

**Pull request merged**
