### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by frju365**
## Problem
- The app is not forcing https, due to which app needs to be manually opened in https to make the communication secure
- Have a look to YunoHost-Apps/nextcloud_ynh#138 for more information

## Solution
- Add redirection
- Get rid of the ini file and merge its content into the pool file.

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Josué
- [x] **Approval (LGTM)** : Josué
- [x] **Approval (LGTM)** : frju365 / Anmol
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/piwigo_ynh%20testing%20(Official)/)

### CODE REVIEW

**Comment by anmol26s** [comment]
My review is for ini file commit not for https. Though it works :D

**Comment by frju365** [comment]
I think I can Approve my PR too (as it was tested in other). So, LGTM for me. 

Let's merge in 3 days !

**Comment by JimboJoe** [comment]
Looks like there's no release message on the forum... :wink:

**Comment by JimboJoe** [comment]
@frju365 I've just posted on the forum. We'd better follow the workflow and advertise the testing AND the stable release next time... :wink:

**Pull request merged**
