### PR TITLE
Upgrade to upstream version 2.10.1

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *The application is not up-to-date*

## Solution
- *Update to latest version 2.10.0*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : frju365 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/piwigo_ynh%20PR40/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by skyfall96** [comment]
i've tried to update in, but it doesn't work.
thx for the pull

**Comment by JimboJoe** [comment]
Hmm... do you have some more information as to what doesn't work (e.g. logs)...?

**Comment by JimboJoe** [comment]
:up:

**Comment by kay0u** [comment]
BTW, we should merge it in testing before, isn't it?

**Comment by JimboJoe** [comment]
Indeed!

**Comment by JimboJoe** [comment]
:up:

**Comment by frju365** [comment]
Let's merge it in 3 days? :-)

**Pull request merged**
